In [89]:
import numpy as np
alip = np.load('ALIP.npy')
footstep = np.load('FOOTSTEP.npy')
hmap = np.load('HMAP.npy')

In [60]:
hmap = hmap[:, 2]

In [61]:
hmap.shape

(5434, 64, 64)

In [88]:
hmap[4100]

array([[-5.31255505e-05, -5.31255505e-05, -5.31255505e-05,
        -5.31255505e-05, -5.31255505e-05, -5.31255505e-05,
        -5.31255505e-05, -5.31255505e-05, -5.31255505e-05,
        -5.31255505e-05, -5.31255505e-05, -5.31255505e-05,
        -5.31255505e-05, -5.31255505e-05, -5.31255505e-05,
        -5.31255505e-05, -5.31255505e-05, -5.31255505e-05,
        -5.31255505e-05, -5.31255505e-05, -5.31255505e-05,
        -5.31255505e-05, -5.31255505e-05, -5.31255505e-05,
        -5.31255505e-05, -5.31255505e-05, -5.31255505e-05,
        -5.31255505e-05, -5.31255505e-05, -5.31255505e-05,
        -5.31255505e-05, -5.31255505e-05, -5.31255505e-05,
        -5.31255505e-05, -5.31255505e-05, -5.31255505e-05,
        -5.31255505e-05, -5.31255505e-05, -5.31255505e-05,
        -5.31255505e-05, -5.31255505e-05, -5.31255505e-05,
        -5.31255505e-05, -5.31255505e-05, -5.31255505e-05,
        -5.31255505e-05, -5.31255505e-05, -5.31255505e-05,
        -5.31255505e-05, -5.31255505e-05, -5.31255505e-0

In [87]:
alip[4100]

array([-0.16209775,  0.01372063, -0.09551194, -0.40320422])

In [86]:
min_index_flat = np.argmin(alip)
min_index = np.unravel_index(min_index_flat, alip.shape)
print("Index of the minimum value:", min_index)
print("Minimum value:", alip[min_index])

Index of the minimum value: (3868, 2)
Minimum value: -8.735346038656344


In [78]:
HMAP_flat = hmap.reshape((hmap.shape[0], -1))
flattened_data = np.concatenate((HMAP_flat, alip), axis=1)
flattened_data[np.isneginf(flattened_data)] = -1
flattened_data.shape

(5434, 4100)

In [79]:
np.save('observationsNN_test1', flattened_data)
np.save('actionsNN_test1', footstep)

In [77]:
np.sum(hmap == -np.inf)

66189

In [91]:
np.save('observationsNN_test2', flattened_data)
np.save('actionsNN_test2', footstep)

In [90]:
HMAP_flat = hmap.reshape((hmap.shape[0], -1))
flattened_data = np.concatenate((HMAP_flat, alip), axis=1)
flattened_data[np.isneginf(flattened_data)] = -1
flattened_data.shape

(5434, 12292)

In [36]:
alip[978]

array([-0.09016039, -1.22341411,  4.04707226, -0.58233997])

In [34]:
min_index_flat = np.argmax(alip)
min_index = np.unravel_index(min_index_flat, alip.shape)

In [35]:
min_index

(978, 2)

In [25]:
o1 = flattened_data[1000:2000]
a1 = footstep[1000:2000]
o1[o1 < -2] = -2

np.save('observationsNN_test1', o1)
np.save('actionsNN_test1', a1)

In [17]:
np.set_printoptions(threshold=np.inf)

In [19]:
o1[140][8000:8500]

array([ 3.98444870e-01,  3.98444870e-01,  3.98444870e-01,  3.98444870e-01,
        3.98444870e-01,  3.98444870e-01,  3.98444870e-01,  3.98444870e-01,
        3.98444870e-01,  3.98444870e-01,  3.98444870e-01,  3.98444870e-01,
        3.98444870e-01,  3.98444870e-01,  3.98444870e-01,  3.98444870e-01,
        3.98444870e-01,  3.98444870e-01,  3.98444870e-01,  3.98444870e-01,
        3.98444870e-01,  3.98444870e-01,  3.98444870e-01,  3.98444870e-01,
        3.98444870e-01,  3.98444870e-01,  3.98444870e-01,  3.98444870e-01,
        3.98444870e-01,  3.98444870e-01,  3.98444870e-01,  3.98444870e-01,
        3.98444870e-01,  3.98444870e-01,  3.98444870e-01,  3.98444870e-01,
        3.98444870e-01,  3.98444870e-01,  3.98444870e-01,  3.98444870e-01,
        3.98444870e-01,  3.98444870e-01,  3.98444870e-01,  3.98444870e-01,
        3.98444870e-01,  3.98444870e-01,  3.98444870e-01,  3.98444870e-01,
        3.98444870e-01,  3.98444870e-01,  3.98444870e-01,  3.98444870e-01,
        3.98444870e-01,  

In [13]:
min_index_flat = np.argmin(o1)
min_index = np.unravel_index(min_index_flat, o1.shape)

print("Index of the minimum value:", min_index)
print("Minimum value:", o1[min_index])

Index of the minimum value: (140, 8253)
Minimum value: -10.0


In [3]:
np.save('observationsNN_test1', flattened_data)
np.save('actionsNN_test1', footstep)

In [18]:
alip1 = np.load('ALIP1.npy')
footstep1 = np.load('FOOTSTEP1.npy')
hmap1 = np.load('HMAP1.npy')

In [19]:
alip2 = np.load('ALIP2.npy')
footstep2 = np.load('FOOTSTEP2.npy')
hmap2 = np.load('HMAP2.npy')

In [20]:
alip3 = np.load('ALIP3.npy')
footstep3 = np.load('FOOTSTEP3.npy')
hmap3 = np.load('HMAP3.npy')

In [21]:
alip4 = np.load('ALIP4.npy')
footstep4 = np.load('FOOTSTEP4.npy')
hmap4 = np.load('HMAP4.npy')

In [22]:
alip5 = np.load('ALIP5.npy')
footstep5 = np.load('FOOTSTEP5.npy')
hmap5 = np.load('HMAP5.npy')

In [23]:
ALIP = np.concatenate((alip, alip1,alip2,alip3,alip4,alip5), axis=0)
HMAP = np.concatenate((hmap, hmap1, hmap2, hmap3, hmap4, hmap5), axis=0)
FOOT = np.concatenate((footstep, footstep1, footstep2, footstep3, footstep4, footstep5), axis=0)

In [24]:
HMAP_flat = HMAP.reshape((HMAP.shape[0], -1))
flattened_data = np.concatenate((HMAP_flat, ALIP), axis=1)

In [25]:
flattened_data[np.isneginf(flattened_data)] = -10

In [26]:
flattened_data.shape

(27125, 12292)

In [27]:
np.save('observationsNN1', flattened_data)
np.save('actionsNN1', FOOT)

In [14]:
alip[0]

array([-0.00501643,  0.00343471, -0.15218358, -0.06036045])

In [16]:
flattened_data[0][-4:]

array([-0.00501643,  0.00343471, -0.15218358, -0.06036045])

In [3]:
HMAP_flat = hmap.reshape((hmap.shape[0], -1))
flattened_data = np.concatenate((HMAP_flat, alip), axis=1)

In [4]:
flattened_data[np.isneginf(flattened_data)] = -5

In [5]:
flattened_data.shape

(5434, 12292)

In [6]:
np.save('observationsNN', flattened_data)
np.save('actionsNN', footstep)

In [54]:
#import sys
#np.set_printoptions(threshold=sys.maxsize)
#hmap[17635,2,:]

In [39]:
#np.isinf(hmap[:,2,:]).any()
#np.sum(np.isinf(hmap[:,2,:]))
#np.where(np.isinf(hmap[:,2,:]))
#hmap[np.isinf(hmap)] = np.finfo(np.float32).max
#np.max(hmap[:,2,:])

True

In [1]:
import numpy as np
obs = np.load('observationsNN.npy')
obs.dtype

dtype('float64')

In [63]:
np.save('observationsNN', flattened_data)

In [64]:
np.save('actionsNN', footstep)

In [12]:
#np.save('observations', x_values)
#np.save('actions', output)

In [7]:
#np.array([-0.2321204, 0.01578688, 0.06369659, -1.16279758]) @ K.T

array([0.67869226, 0.00476704])